name: env_example
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.7
 - gym
 - jupyterlab
 - pandas
 - scikit-learn
 - jupyter
 - notebook
 - pip
 - pip:
   - ray[rllib,debug,tune,default]
   - tensorflow==2.4.0